import { PortfolioStatus } from '@/enums/portfolio';
import { Portfolio } from '@/types/portfolio';

export const portfoliosData: Portfolio[] = [
  {
    id: 1,
    name: 'dropright',
    translationKey: 'dropright',
    image: `/portfolio/dropright.png`,
    link: 'https://dropright.com/',
    status: PortfolioStatus.OPEN,
    techStack: [
      'Next.js',
      'TypeScript',
      'Tailwind CSS',
      'React Query/RTK Query',
      'shadcn ui',
    ],
  },
  {
    id: 2,
    name: 'reg-tu',
    translationKey: 'regTu',
    image: '/portfolio/reg-tu.png',
    link: 'https://reg.tu.ac.th/',
    status: PortfolioStatus.OPEN,
    techStack: [
      'Next.js',
      'TypeScript',
      'Tailwind CSS',
      'React Query/RTK Query',
      'shadcn ui',
    ],
  },
  // {
  //   id: 3,
  //   name: 'education-fair',
  //   translationKey: 'educationFair',
  //   image: `/portfolio/tcg.png`,
  //   link: null,
  //   status: PortfolioStatus.OPEN,
  //   techStack: ['Next.js', 'TypeScript', 'Tailwind CSS'],
  // },
  // {
  //   id: 4,
  //   name: 'wonder-seas',
  //   translationKey: 'wonderSeas',
  //   image: `/portfolio/tcg.png`,
  //   link: 'https://wonder-seas.com/en',
  //   status: PortfolioStatus.OPEN,
  //   techStack: ['Next.js', 'TypeScript', 'Tailwind CSS'],
  // },
  // {
  //   id: 5,
  //   name: 'ot-bar',
  //   translationKey: 'otBar',
  //   image: `/portfolio/tcg.png`,
  //   link: null,
  //   status: PortfolioStatus.OPEN,
  //   techStack: [
  //     'Next.js',
  //     'TypeScript',
  //     'Tailwind CSS',
  //     'React Hook Form',
  //     'Zod',
  //   ],
  // },
  // {
  //   id: 6,
  //   name: 'tcg-thailand',
  //   translationKey: 'tcg',
  //   image: `/portfolio/tcg.png`,
  //   link: 'https://www.tcgthailand.com/',
  //   status: PortfolioStatus.CLOSE,
  //   techStack: ['Vue', 'Nuxt.js', 'JavaScript', 'Tailwind CSS'],
  // },
  {
    id: 7,
    name: 'fan-delivery',
    translationKey: 'fanDelivery',
    image: `/portfolio/fan.png`,
    link: 'https://fandelivery.net/',
    status: PortfolioStatus.CLOSE,
    techStack: ['Next.js', 'React', 'JavaScript', 'Tailwind CSS'],
  },
  {
    id: 8,
    name: 'jetlag',
    translationKey: 'jetlag',
    image: `/portfolio/jetlag.png`,
    link: 'https://www.jetlagapplication.com/',
    status: PortfolioStatus.CLOSE,
    techStack: ['Vue', 'Nuxt.js', 'JavaScript', 'Tailwind CSS'],
  },
  {
    id: 9,
    name: 'gameconnext',
    translationKey: 'gameconnext',
    image: `/portfolio/gameconnext.png`,
    link: 'http://www.gameconnext.com/',
    status: PortfolioStatus.CLOSE,
    techStack: ['Vue', 'Nuxt.js', 'JavaScript', 'Tailwind CSS'],
  },
];
